#!/usr/bin/env bash

while read -r line; do
    verb=$(cut -d ' ' -f 1 <<< "$line")
    [ "$verb" != "add" ] && continue

    id=$(awk -F '/' '{print $5}' <<<"$line")
    name=$(cut -d ' ' -f 2 <<< "$line")
    notable=$(cut -d ' ' -f 3 <<< "$line")
    if [ "$notable" = "not" ]; then
        notable=0
        flag=$(cut -d ' ' -f 4 <<< "$line")
        race=$(cut -d ' ' -f 5 <<< "$line")
    else
        notable=1
        flag=
        race=
    fi
    echo "$id,$name,,$race,$flag,$notable"
done
